### ISSUE TITLE
libmimalloc-sys fails to build for wasm target on Windows

### ISSUE THREAD

**Issue by Boscop** [purpleprotocol/mimalloc_rust#11]
Not sure if this allocator is intended to also work for wasm, but in my frontend I need speed more than size (it's a UI for a desktop application), so I thought I'd try it..
But it fails to build for wasm:
```
error[E0432]: unresolved imports `libc::c_void`, `libc::size_t`
 --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\libmimalloc-sys-0.1.9\src\lib.rs:3:12
  |
3 | use libc::{c_void, size_t};
  |            ^^^^^^  ^^^^^^ no `size_t` in the root
  |            |
  |            no `c_void` in the root

error: could not compile `libmimalloc-sys`.
```

**Comment by octavonce** [comment]
@Boscop While the original mimalloc library compiles on WASM, the wrapper uses rust's `libc` to do ffi calls. Unfortunately, there is no WASM target available for `libc`. Check [this](https://github.com/rust-lang/libc/issues/858) out.

**Comment by octavonce** [comment]
@Boscop Sure, that makes sense
