### ISSUE TITLE
Update to upstream's latest version?: 2.1.6

### ISSUE THREAD

**Issue by ryoqun** [purpleprotocol/mimalloc_rust#120]
Hi, thanks for maintainng this crate.

As a context, we're now evaluating mimalloc (https://github.com/anza-xyz/agave/pull/1250). If possible, could you update this crate to follow the latest upstream version? Thanks in advance.

The upstream released v2.1.6 recently:

```
Latest release tag: v2.1.6 (2024-05-13):

2024-05-13, v1.8.6, v2.1.6: Fix build errors on various (older) platforms. Refactored aligned allocation.
```

https://github.com/microsoft/mimalloc/releases/tag/v2.1.6

**Comment by octavonce** [comment]
Done

**Comment by ryoqun** [comment]
@octavonce really thanks!
