### ISSUE TITLE
Update to upstream's latest version?: 2.1.7

### ISSUE THREAD

**Issue by ryoqun** [purpleprotocol/mimalloc_rust#124]
hi, me again. really thanks for updating 2.1.6 previously :)

As a context, we're _still_ evaluating mimalloc (https://github.com/anza-xyz/agave/pull/1250). If possible, could you update this crate to follow the latest upstream version? Thanks in advance.

The upstream released v2.1.7:

```
Latest release tag: v2.1.7 (2024-05-21):
2024-05-21, v1.8.7, v2.1.7: Fix build issues on less common platforms. Started upstreaming patches from the CPython https://github.com/python/cpython/issues/113141#issuecomment-2119255217. Upstream vcpkg patches.
```

https://github.com/microsoft/mimalloc/releases/tag/v2.1.7

**Comment by octavonce** [comment]
Sorry I seem to have missed the last version.

Pushed the new release now.
