### ISSUE TITLE
Debug builds print stats to stderr

### ISSUE THREAD

**Issue by Speedy37** [purpleprotocol/mimalloc_rust#4]
By default, mimalloc print stats to stderr at some events (thread exit, process exit, ...).

I don't think this is desired.

This is controlled by the `#define MI_DEBUG` in C and can be overwritten though C flags in cmake.

**Comment by Canop** [comment]
This is a blocking problem and it makes mimalloc look like just an experiment. What's the status on this ?

**Comment by Speedy37** [comment]
I can fix it now, I was waiting to see how cmakefiles evolve in the microsoft mimalloc repository.

In the current form, setting `MI_DEBUG` to `0` via build.rs should fix this.

**Comment by octavonce** [comment]
@Canop Note that this only happens in debug builds currently. This is because mimalloc's CMakeLists.txt turns on MI_DEBUG if the target directory or any of it's parents is named "debug".
