### ISSUE TITLE
libmimalloc-sys is missing #![no_std] and injects std into my no_std crate

### ISSUE THREAD

**Issue by asrael** [purpleprotocol/mimalloc_rust#59]
Error message I receive during the build from my crate:

error[E0152]: found duplicate lang item `panic_impl`
28 | fn panic(_: &PanicInfo) -> ! { loop {} }
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the lang item is first defined in crate `std` (which `libmimalloc_sys` depends on)

**Comment by asrael** [comment]
Not entirely sure it actually is compiling in std to my crate. I am a no_std newb, so this maybe a non-issue. Feel free to close if so :)

**Comment by asrael** [comment]
See PR comment: This has probably gone stale, also it's a very simple change once the platform deps were fixed in a previous release from the cmake-rs -> cc-rs change.

**Comment by LANCENET** [comment]
> See PR comment: This has probably gone stale, also it's a very simple change once the platform deps were fixed in a previous release from the cmake-rs -> cc-rs change.
