### ISSUE TITLE
Possible memeory leak

### ISSUE THREAD

**Issue by Licenser** [purpleprotocol/mimalloc_rust#6]
Hi,
first of all my apologies since this is going to start off as a terrible issue as pretty much all I can say is "it doesn't work" ... please bear with me non the less.

In an application, I'm working on (currently not open source :/) switching from jemalloc to mimalloc causes memory to grow until the system is shut down the process for OOM.

I'm not an expert at debugging those kinds of things, so I would love to get a few points on how to get data that will make this issue useful. So far all I can tell is switching from one to the other either introduces or removes the issue.

**Comment by octavonce** [comment]
@Licenser Hi, it is probably this bug, which is a bug in the microsoft mimalloc library itself: https://github.com/microsoft/mimalloc/issues/100

**Comment by Licenser** [comment]
Ohhh wow! thanks that's a good link, I should have thought about looking at the upstream tracker :/ sorry.

**Comment by octavonce** [comment]
@Licenser No worries. Will publish a new release when it is fixed upstream.

**Comment by Licenser** [comment]
Thank you!

**Comment by Licenser** [comment]
I don't think this was actually resolved, with 1.6 I'm still seeing the leaking behaviour.
