### ISSUE TITLE
libmimalloc-sys  crate outdated

### ISSUE THREAD

**Issue by Licenser** [purpleprotocol/mimalloc_rust#7]
Hi,
I was chasing the memory leak mentioned in #6 and after much forth and back it turns out that the current (fixed) mimalloc crate still depends on an old `libmimalloc-sys ^0.1.4` crate that wasn't updated to the post-memory leak release. Could you bump the `libmimalloc-sys` crate to include the fixes for #6?

many thanks in advance.

**Comment by octavonce** [comment]
@Licenser Hey there! I just published a new release now which should contain the fixes. I also yanked all other releases until this one to prevent potential user issues down the road with older versions.
