### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by feld** [purpleprotocol/mimalloc_rust#95]
Needs this commit https://github.com/microsoft/mimalloc/commit/bcbcc343ec658382bc6ab59615590c1cdb75ef6e

**Comment by octavonce** [comment]
@feld The latest version is built with the master branch of mimalloc.

**Comment by octavonce** [comment]
@ThatOneCalculator  That commit is in the master branch. How is it not working?

**Comment by ThatOneCalculator** [comment]
Read the logs here: https://github.com/meilisearch/meilisearch/issues/3806

**Comment by octavonce** [comment]
@ThatOneCalculator I did. That commit is already in the master branch and mimalloc rust is built against that. I see `libmimalloc-sys v0.1.32` produces the error while `libmimalloc-sys v0.1.33` contains the freeBSD fixes.

**Comment by octavonce** [comment]
Closing this as this is fixed in the latest version.
